

BASE_PACKAGES = [
    "tumbler",
    "ffmpegthumbnailer",
    "lsd",
    "alacritty",
    "calc",
    "automake",
    "blueman",
    "bluez",
    "bluez-utils",
    "fakeroot",
    "feh",
    "firefox",
    "fish",
    "dpkg",
    "gcc",
    "git",
    "lxappearance",
    "thunar",
    "neofetch",
    "papirus-icon-theme",
    "polybar",
    "autoconf",
    "mpc",
    "pulseaudio",
    "ranger",
    "reflector",
    "rofi",
    "rofi-calc",
    "calcurse",
    "rofi-emoji",
    "sudo",
    "slop",
    "tree",
    "unrar",
    "zip",
    "unzip",
    "uthash",
    "xarchiver",
    "xfce4-power-manager",
    "xfce4-settings",
    "xorg-xbacklight",
    "cmake",
    "clang",
    "gzip",
    "make",
    "vlc",
    "usbutils",
    "picom",
    "ffmpeg",
    "p7zip",
    "xclip",
    "gpick",
    "wget",
    "ueberzug",
    "netctl",
    "light",
    "breeze",
    "vulkan-intel",
    "intel-ucode",
    "ttf-jetbrains-mono",
    "ttf-jetbrains-mono-nerd",
    "ttf-fira-code",
    "ttf-iosevka-nerd",
    "alsa-plugins",
    "alsa-tools",
    "alsa-utils",
    "python-pyalsa",
    "pulseaudio-alsa",
    "pulseaudio",
    "feh"
]

DEV_PACKAGES = [
    "screenkey",
    "timeshift",
    "pinta",
    "gnome-firmware",
    "neovim",
    "obs-studio",
    "telegram-desktop",
    "code",
    "deluge-gtk",
    "flameshot",
    "obsidian",
    "python-pip"
]

AUR_PACKAGES = [
    "i3lock-color",
]

GNOME_OFFICIAL_TOOLS = [
    "evince",
    "gnome-calculator",
    "gnome-disk-utility",
    "gucharmap",
    "gthumb",
    "gnome-clocks"
]

